### ISSUE TITLE
install异常

### ISSUE THREAD

**Issue by jiangqideng** [syaning/zhihuapi-py#1]
如下：
```
C:\Users\jiang>pip install zhihuapi
Collecting zhihuapi
  Using cached zhihuapi-0.5.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jiang\appdata\local\temp\pip-build-yyjm1r\zhihuapi\setup.py", line 4, in <module>
        with open('README.rst', encoding='utf8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\jiang\appdata\local\temp\pip-build-yyjm1r\zhihuapi\
```

**Comment by syaning** [comment]
@jiangqideng 你用的应该是python2.x吧？目前只支持python 3.x，你看下是不是这个问题。

**Comment by jiangqideng** [comment]
@syaning 嗯，是的，换到python3，前面正常了，但后面还得去安装Visual C++，懒得折腾了...

**Comment by syaning** [comment]
@jiangqideng 为什么会需要 Visual C++ 。。。

**Comment by jiangqideng** [comment]
@syaning 如下：
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.co
m/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\jiang\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\j
iang\\AppData\\Local\\Temp\\pip-build-gn5yobyr\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\jiang\AppData\Local\Temp\pip-ccbwdwcq-recor
d\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jiang\AppData\Local\Temp\p
ip-build-gn5yobyr\lxml\
```

**Comment by syaning** [comment]
@jiangqideng 我知道了，应该是因为依赖了pyquery这个包，而pyquery依赖了lxml，而lxml在windows下安装好像容易出问题。

你可以试下 http://www.lfd.uci.edu/~gohlke/pythonlibs/ 这里build好的 lxml 包。

**Comment by jiangqideng** [comment]
@syaning 可以了，感谢！
